_base_:
- ../model/snn2d.yml
- ../dataset/solar.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 64
  aggregate: True
  beta: 2e-6

network:
  type: SNN2d
  num_steps: 4
  layers: 2
  hidden_size: 64
  encoder_type: conv
  use_cluster: True  # Enable clustering
  use_ste: True
  gpu_id: 2
  n_cluster: 3
  use_all_zero: False  # Use all-zero cluster probabilities
  use_all_random: False  # Use all-random cluster probabilities
  d_model: 512

runtime: 
  seed: 42
  output_dir: ./outputs/snn_cluster_solar