_base_:
- ../model/spikegru.yml
- ../dataset/etth1.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 96

runner:
  type: vsts
  batch_size: 44
  aggregate: False
  out_size: 96
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 5
  denormalize: True
  valid_variates: 137
  beta: 2e-6

network:
  type: SNNGRU2d
  num_steps: 4
  layers: 1
  hidden_size: 128
  encoder_type: conv
  use_cluster: True  # Enable clustering
  use_ste: True
  gpu_id: 2
  n_cluster: 3
  use_all_zero: False  # Use all-zero cluster probabilities
  use_all_random: False  # Use all-random cluster probabilities
  d_model: 256

runtime:
  seed: 42
  output_dir: ./outputs/spikegru_cluster_solar