_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  type: TSMSDataset
  file: data/ETTh2_wide.txt
  window: 12
  horizon: 24
  train_ratio: 0.7
  test_ratio: 0.1
  raw_label : False

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 256
  aggregate: True
  beta: 2e-6

network:
  type: SNN_TCN2D
  kernel_size: 3
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.
  num_steps: 4
  hidden_size: 64
  encoder_type: conv
  pe_type: neuron
  pe_mode: concat
  num_pe_neuron: 40
  neuron_pe_scale: 10000.0
  use_cluster: True  # Enable clustering
  use_ste: True
  gpu_id: 2
  n_cluster: 3
  use_all_zero: False  # Use all-zero cluster probabilities
  use_all_random: False  # Use all-random cluster probabilities
  d_model: 512

runtime: 
  seed: 42
  output_dir: ./outputs/NeuronPE_spiketcn2d_horizon=24_metr-la