_base_:
- ../dataset/traffic.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 24
  normalize: 1

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 64
  aggregate: True
  beta: 2e-6

network:
  type: Spikformer
  dim: 256
  d_ff: 1024
  depths: 2
  num_steps: 4
  heads: 8
  pe_type: none
  pe_mode: concat
  num_pe_neuron: 40
  neuron_pe_scale: 10000.0
  encoder_type: conv
  use_cluster: True  # Enable clustering
  use_ste: True
  gpu_id: 2
  n_cluster: 3
  use_all_zero: False  # Use all-zero cluster probabilities
  use_all_random: False  # Use all-random cluster probabilities
  d_model: 512

runtime:
  seed: 39
  output_dir: ./outputs/NoPE_Spikformer_horizon=24_traffic